CREATE TABLE Blogs (
	BlogId INT PRIMARY KEY IDENTITY(1,1),
	Title NVARCHAR(120) NOT NULL,
	ImageFileName NVARCHAR(250), 
	Summary NVARCHAR(250),
	Content NVARCHAR(MAX),
	AuthoredBy NVARCHAR(256) NOT NULL,
	AuthoredOn DATETIME NOT NULL DEFAULT(GETDATE()),
	ModfiedBy NVARCHAR(256) NOT NULL,
	ModifiedOn DATETIME NOT NULL DEFAULT(GETDATE()),
	Active BIT NOT NULL DEFAULT(0)
)